### ISSUE TITLE
Minifying while maintaining filename

### ISSUE THREAD

**Issue by yusuphwickama** [adamlui/minify.js#13]
Hello. 

I love this project. I'm having a challenge, however. 
How can I minify my file without changing the name to include ".min.js"?

I want the script to go through a folder and replace all files with the minified version. That part I've already figured out, but now I want to remove the ".min.js" and just make it ".js"

**Comment by adamlui** [comment]
Hey @yusuphwickama thanks for loving it! You just want it so you can use CLI w/ a flag like `--no-filename-change` to output /file.js to /min/file.js instead of /min/file.min.js?

Also how did you find the project?

**Comment by adamlui** [comment]
@yusuphwickama I added the `--no-filename-change` CLI option to [v1.8.0](https://github.com/adamlui/minify.js/releases/tag/node-v1.8.0), can you update and tell me will it meet your need?

If project dependency, from project root:
```
npm update @adamlui/minify.js --save
```

If global installation:
```
npm update -g @adamlui/minify.js
```
